### ISSUE TITLE
[技术咨询] webrtc: how to play video stream on browser

### ISSUE THREAD

**Issue by pubpy2015** [ZLMediaKit/ZLMediaKit#1080]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

WebRTC

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

I am beginner for WebRTC
Follow instruction: https://blog.csdn.net/byna11sina11/article/details/119786889
I can build MediaServer with enable WebRTC.
- using your WebRtcClient i can play video stream:
 
![ảnh](https://user-images.githubusercontent.com/59004953/131623276-830ce5f7-1a75-494d-a301-18ae01b95cd8.png)

but when put this url http://127.0.0.1:8081/index/api/webrtc?app=proxy&stream=cam8&type=play on browser (Chrome, Edge, FireFox) i am get the error:
{
   "code" : -400,
   "msg" : "Assertion failed: (!origin.empty()), function RtcSession::checkValid, file D:\\20210901_2751\\ZLMediaKit\\webrtc\\Sdp.cpp, line 1330."
}

please help me fix this.

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
`/index/api/webrtc` is not a way for play, it just a way for exchange `sdp` for `webrtc`.
When we make connection of webrtc, we need exchange `sdp`, and `/index/api/webrtc` is to do this.

**Comment by xia-chu** [comment]
When we use webrtc on browser, we need use it`s javascript api, and the project `ZLMRTCClient.js`  is to do this.

**Comment by pubpy2015** [comment]
Thanks,

Oh, because i think WebRTC is plugin free, can play directly on web browser.
I have seen some video conference system using WebRTC and can play video directly on browser.
Other question:
Does the ZLMRTCClient.js is support H265 video stream ?

**Comment by xia-chu** [comment]
webrtc do not support h265!



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: pubpy2015 ***@***.***&gt;
发送时间: 2021年9月2日 11:31
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [技术咨询] webrtc: how to play video stream on browser (#1080)





 
Thanks,
 
Oh, because i think WebRTC is plugin free, can play directly on web browser.
 I have seen some video conference system using WebRTC and can play video directly on browser.
 Other question:
 Does the ZLMRTCClient.js is support H265 video stream ?

**Comment by pubpy2015** [comment]
Thanks for your support,

Other question about SSL:
Is any way to run MediaServer.exe to automatic load ssl.pem instead of run command with parametter: ./MediaServer -s ./ssl.pem

(double click to run or debug on VissualStudio)

**Comment by xia-chu** [comment]
you can rename ssl.pem to ssl.p12, MediaServer load it default



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: pubpy2015 ***@***.***&gt;
发送时间: 2021年9月2日 12:34
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [技术咨询] webrtc: how to play video stream on browser (#1080)





 
Thanks for your support,
 
Other question about SSL:
 Is any way to run MediaServer.exe to automatic load ssl.pem instead of run command with parametter: ./MediaServer -s ./ssl.pem
 
(double click to run or debug on VissualStudio)

**Comment by pubpy2015** [comment]
Thanks,

I will try it.
